version: '3'
services:

  mysql:
    image: mysql:8.0
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      npm:
        aliases:
          - ${STACK_NAME}-mysql

  wordpress:
    image: wordpress:6.5.3-php8.1-apache
    hostname: wordpress-1
    restart: always
    volumes:
      - wp-content:/var/www/html/wp-content
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: ${STACK_NAME}-mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - npm

volumes:
  mysql:
  wp-content:

networks:
  npm:
    name: npm_network